### ISSUE TITLE
Everyone has your skin after rejoin with Nemisys

### ISSUE THREAD

**Issue by ghost** [iTXTech/Nemisys#53] opened 2016-09-23 21:58 UTC
When I join a server, and then rejoin the old server, then everyone has my skin (before I joined the other server everyone had his skin). Can you fix it?

**Comment by xZeroMCPE** [comment] 2016-09-23 22:08
It can be fixed easy :) 

Just re-set the player skin onJoin event. Worked fine :)

But again, this should be fixed within Nemisys.

EDIT: Works but if you rejoin 1-2 times you will start seeing your skin.

**Comment by ghost** [comment] 2016-09-24 11:21
Good idea, maybe it will work with a task after playerjoinevent?

**Comment by FilleDev** [comment] 2016-09-24 11:25
hmmmm

**Comment by xZeroMCPE** [comment] 2016-09-24 15:43
Here's an example:

`
public function onJoin(PlayerJoinEvent $event){

$player = $event->getPlayer();
		$player->despawnFromAll();
$player->setSkin($player->getSkinData(), $player->getSkinId());
        $player->spawnToAll();
 }
}`

But again, like @MyNameIsTriXz said, a task would be better. Since the code above works but if you rejoin 1-2 times you will start seeing a duplicate of your skin on other servers. So maybe test it through a task?

**Comment by boybook** [comment] 2016-10-18 00:21
This is a stubborn bug in Nukkit.
Maybe I can't grasp the best time to send the skin data.

**Closed as completed** 2017-07-06 13:45 UTC
