### ISSUE TITLE
Client freezes when opening pause menu

### ISSUE THREAD

**Issue by evolvedtm** [iTXTech/Nemisys#13] opened 2016-08-09 17:33 UTC
When a client opens the ingame pause menu, it freezes their app and they have to force-close it

OS: Ubuntu 64bit

**Comment by evolvedtm** [comment] 2016-08-09 18:01
It happens on a server you're transferred to not the main one

**Comment by SleepSpace9** [comment] 2016-08-09 20:25
Confirmed, same issue. I'm still waiting for progress in this project. :pensive:

Server: Genisys (build/commit unknown, tested last week) / PHP 7.0.3 / Ubuntu 14.0.4
Client: Amazon Fire (Android derivative) and Windows 10 Edition - both v0.15.4

**Comment by Guillaume351** [comment] 2016-08-11 08:30
Same issue.
Server : Nukkit with latest SynapseAPI.
Client : Win 10 / iOS

**Comment by jarne** [comment] 2016-08-11 14:18
Same here,
Nemisys and Genisys latest build on Debian 8.5 x64, PHP 7.0.9.
Clients are iPad and iPhone with iOS 10, and Galaxy Tab A with Android 6.1.

**Comment by markeev** [comment] 2016-08-12 08:51
Same issue.
Server : Nemisys + Genisys.
Client : ios / android

**Comment by jarne** [comment] 2016-08-12 12:19
Someone from @iTXTech @PeratX @boybook can help? Seems to be a serious issue because the client always freezes. Looks like it would only happen if more players are online, so it's not always reproducible. The bug is there since 00da207.

**Comment by intagaming** [comment] 2016-08-13 15:42
Something happened when Nemisys starts to transfer. If you leave "disable-raklib" to false and connect not by Nemisys but the Raklib itself to the main server, everything's fine.
However if you connect to the main server by Nemisys, the packets just doesn't right. They are not sending packet anymore. I've try to hide their name by "DataPacketSendEvent" but it doesn't pop up or just doesn't actually work.
By short, the Nemisys connection is fine. The Nemisys's Transfering Packet is not right.
Also for reproduce: The client for the bug must log in after other clients have been logged in. 2 clients didn't do the trick (as @jjplaying ^).

**Comment by dbaonam99** [comment] 2016-08-15 01:46
Chim to mới fix được

**Comment by MattWAnderson** [comment] 2016-08-19 15:45
Same issue, latest Nemisys on CentOS 6.6 & Windows 10. - Using Nemisys to transfer to a main hub server. No other servers added due to this issue. Typically 100+ Online during testing.

**Comment by markeev** [comment] 2016-08-19 19:08
Will u fix this fckn bug?

**Comment by StaticGamerYT** [comment] 2016-08-20 08:36
@jjplaying How do you know the bug is there since 00da207? I compiled a build before it, but it still happens.

**Comment by SleepSpace9** [comment] 2016-08-20 08:47
It could also be that the bug exists since MCPE v0.15.4 with the new protocol version 82. It came at about the same time. Maybe someone can trace the traffic and see what's wrong with the packets.

**Comment by jarne** [comment] 2016-08-20 08:48
I think it's just a problem with the new PlayerListPacket by Nemisys, because it's since that commit

**Comment by jarne** [comment] 2016-08-20 08:49
@StaticGamerYT Really? Maybe I didn't tested enough 🙃

**Comment by SleepSpace9** [comment] 2016-08-20 08:52
@jjplaying I also tried with the build before SPPv6 and still have the same issues.

**Comment by jarne** [comment] 2016-08-20 09:24
Okay, but it is likely to be an issue with the PlayerList because it only happens when more player are online and in the options menu, and the only thing which is communicating with TH server in the options menu is the PlayerList.

**Comment by StaticGamerYT** [comment] 2016-08-20 10:34
@jjplaying Wanna try to fix it together?

**Comment by SleepSpace9** [comment] 2016-08-20 17:24
The freeze has been solved with the last Genisys commits made by @MrGenga. YAY!
Still the question, whats about Nukkit?

_Edit: The PR (https://github.com/iTXTech/Genisys/pull/1720) I successfully tested is not merged at the moment. I hope it will be merged later..._

**Comment by Encritary** [comment] 2016-08-20 17:34
@SleepSpace9 Nukkit is very slow in development, not like Genisys. It only rewrite of PHP PocketMine with some changes, there is memory leaks, crashes, not stable level providers and more.... I recommend to use other software(like MiNET, or thats Genisys). My BedWars Nukkit servers"eat" 25 GB of RAM, but when I did it in PHP(Genisys), it more stable. If you want the best stability, use MiNET. I think about MiNET Nemisys support(is hard  for me, I only started learning C#, but know Java very well)
#offtop

**Comment by jarne** [comment] 2016-08-20 20:49
Great!

**Comment by ArrowDCA** [comment] 2016-08-20 20:50
Finally no more crashes

**Comment by ghost** [comment] 2016-08-24 19:52
@intagaming I'm creating new issue. You can help me with this error please? Or @MrGenga or @MattWAnderson or anyone know how use?

**Comment by MattWAnderson** [comment] 2016-08-24 19:58
Email me. Matt@MattWAnderson.com

Servers running it are at hub.pocketminers.com

**Comment by ghost** [comment] 2016-08-24 20:00
@MattWAnderson You can go my telegram group please? https://telegram.me/joinchat/Ca8L9T9P01PtR1bOEwtxuw

**Comment by ghost** [comment] 2016-08-24 20:09
@MattWAnderson I'm sending you one message on yahoo mail.

**Comment by SleepSpace9** [comment] 2016-09-17 14:36
I think this issue can be closed because it has been solved with the merge of this PR: https://github.com/iTXTech/Genisys/pull/1720.

**Closed as completed** 2016-09-17 22:20 UTC
